// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUPdnGqBbaHubQaxmZu7lfdmEjff_FvvY',
    appId: '1:355256939933:web:bb605de13fbe96380deb74',
    messagingSenderId: '355256939933',
    projectId: 'flowpi-app',
    authDomain: 'flowpi-app.firebaseapp.com',
    storageBucket: 'flowpi-app.firebasestorage.app',
    measurementId: 'G-WTJFSM3JZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2QuwihXdhMzMB_UjByHYvFqD9olBr_Oo',
    appId: '1:355256939933:android:6ec9bc4c685ca7020deb74',
    messagingSenderId: '355256939933',
    projectId: 'flowpi-app',
    storageBucket: 'flowpi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGO8EPMNb9gX5m-NwBJrBE-ja7_jZRQl8',
    appId: '1:355256939933:ios:3fe64f0c3ec2d01f0deb74',
    messagingSenderId: '355256939933',
    projectId: 'flowpi-app',
    storageBucket: 'flowpi-app.firebasestorage.app',
    iosClientId: '355256939933-3vbcm0brp3pq1s7hnef8uolmigh2med7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flowphi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUPdnGqBbaHubQaxmZu7lfdmEjff_FvvY',
    appId: '1:355256939933:web:7d74cc244e7d8fd30deb74',
    messagingSenderId: '355256939933',
    projectId: 'flowpi-app',
    authDomain: 'flowpi-app.firebaseapp.com',
    storageBucket: 'flowpi-app.firebasestorage.app',
    measurementId: 'G-02K28C22JV',
  );

}